GameConsuleWebStore/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameConsuleWebStore.Data;
using GameConsuleWebStore.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography.X509Certificates;
using Microsoft.EntityFrameworkCore.Internal;

namespace GameConsuleWebStore.Controllers
{
    public class OrdersController : Controller
    {
        private readonly GameConsuleWebStoreContext _context;


        public OrdersController(GameConsuleWebStoreContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> ShowOrders(int id)
        {
            List<Order> result = new List<Order>();
            if(HttpContext.Session.GetString("UserId")!=null)
            {
                if (_context.Order.Where(o=>o.User.Id==id).ToList().Count == 0)
                {
                    ViewBag.Show = "There is no any Orders. Please wait until create a new one";
                    return View();
                }
                else
                {
                    result = _context.Order.Where(p => p.User.Id == id).ToList();
                }
            }
            else
            {
                //return RedirectToAction("Login", "Users");
                return RedirectToAction("Login", "Users", new { messageAlert = "You need to Login first." });
            }
            return View(result);
        }



        // GET: Orders
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("UserType") != "Admin")
            {
                return RedirectToAction("Login", "Users", new { messageAlert = "You are not admin.\nTry Login Admin member first." });
            }
            return View(await _context.Order.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id,string messageAlert)
        {
            ViewBag.AlertSuccesful = messageAlert;

            if (id == null)
            {
                return NotFound();
            }

            //Taking the order with all includes -> ProductOrders+ Product + Items for Order
            var order = await _context.Order.Include(po => po.ProductOrders).Include(po => po.ItemsPerOrder).ThenInclude(o => o.Product).FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            //Taking the items per order for the view
            List<Item> ListOfItemsPerOrder = new List<Item>();
            foreach (Item t in order.ItemsPerOrder)
            {
                ListOfItemsPerOrder.Add(t);
            }
            ViewBag.ListOfItemsPerOrderID = ListOfItemsPerOrder;



            return View(order);
        }



        public IActionResult Create()
        {
            string messageForCreating="";
            if (HttpContext.Session.GetString("UserId") == null)
            {
                messageForCreating = "You Need To Login For Purchasing On Our Site.";
            }
            ViewBag.AlertForCreating = messageForCreating;
            List<Item> itt = GameConsuleWebStore.Controllers.ShoppingCartController.cartTemp;
            List<SelectListItem> items = new List<SelectListItem>();

            ViewBag.itemsForOrder = itt;
            double AmountTotal = 0;
            //Showing the prodcuts from the cart to the Order-Create-View
            foreach (Item it in itt)
            {
                items.Add(new SelectListItem { Text = it.Product.Name, Value = it.Product.ProductId.ToString(), Selected = true });
                //View-Total-Amount-for order
                AmountTotal += it.Quantity * it.Product.Price;
                it.Product.StockUnit = it.Product.StockUnit - it.Quantity;
            }

           ViewBag.cartItemsData = items;
            ViewData["ProductId"] = items;

            ViewBag.TotalAmountForOrder = AmountTotal;
            ViewBag.DateYearCurrently = DateTime.Today.Year;
            ViewBag.DateMonthCurrently = DateTime.Today.Month;
            ViewBag.DateDayCurrently = DateTime.Today.Day;

            return View();
        }



        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DateOrder")] Order order,int[] ProductId)
        {

            if (ModelState.IsValid)
            {
                //--------Connect The user to the order------
                //MUST LOGIN FIRST
                if(HttpContext.Session.GetString("UserId")!=null)
                {
                    order.User = _context.User.First(x => x.Id.ToString().Equals(HttpContext.Session.GetString("UserId")));
                }
                else
                {
                    return RedirectToAction("Login", "Users", new { messageAlert = "You need to Login first for purchasing." });
                }
                //Adding the "many to many" function -> The OrderCntroller Creating a new Order with many products.
                order.DateOrder = DateTime.Now;

                order.ProductOrders = new List<ProductOrder>();
                foreach(var id in ProductId){
                    order.ProductOrders.Add(new ProductOrder() { ProductId = id, OrderId = order.Id });
                }

                _context.Add(order);
                await _context.SaveChangesAsync();

                List<Item> itt = GameConsuleWebStore.Controllers.ShoppingCartController.cartTemp;

                order.ItemsPerOrder = itt;
                await _context.SaveChangesAsync();

                //ERASE THE SESSION And Empty the static List cart
                GameConsuleWebStore.Controllers.ShoppingCartController.cartTemp = new List<Item>();
                HttpContext.Session.Remove("Cart");
                HttpContext.Session.Remove("CartNumOfItems");


                return RedirectToAction("Details", new { id = order.Id , messageAlert ="Order Succesfully!" });
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DateOrder")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order2 = await _context.Order.Include(x=>x.ItemsPerOrder).FirstAsync(o=>o.Id==id);

            //*********Removing the entity "Item" because its one to many realationship**********
            foreach(Item idItem in order2.ItemsPerOrder)
            {
                var item = await _context.Item.FindAsync(idItem.ItemId);
                _context.Item.Remove(item);
            }
            var order = await _context.Order.FindAsync(id);
            await _context.SaveChangesAsync();
            _context.Order.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.Id == id);
        }
    }
}

GameConsuleWebStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameConsuleWebStore.Data;
using GameConsuleWebStore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GameConsuleWebStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        public static List<Item> cartTemp = new List<Item>();
        private GameConsuleWebStoreContext de;
        public ShoppingCartController(GameConsuleWebStoreContext de)
        {
            this.de = de;
        }


        //Procced To CheckOut - Redirect to order-creat with the data we need
        public IActionResult ProcceedToCheck()
        {
            return RedirectToAction("Create", "Orders");
        }


        public IActionResult Index()
        {
            List<Item> cart = cartTemp;

            ViewBag.CounterCart = cartTemp.Count;

            if (cart.Count==0)
            {
                ViewBag.cart = cart;
            }
            else
            {
                HttpContext.Session.SetString("Cart", cart.ToString());
                ViewBag.cart = cart;
            }
            /////////////////////////////////////////////////////////////////////////////////
            HttpContext.Session.SetString("CartNumOfItems", cartTemp.Count.ToString());
            return View("Cart");
        }

        private int isExistingProduct(int id)
        {
            List<Item> newCart = cartTemp;
            for(int i=0;i<newCart.Count;i++)
            {
                if (newCart[i].Product.ProductId == id)
                    return i;
            }
            return -1;
        }

        public IActionResult Delete(int id)
        {
            int index = isExistingProduct(id);
            List<Item> cart = cartTemp;

            cart.RemoveAt(index);
            HttpContext.Session.SetString("Cart", cart.ToString());
            ViewBag.cart = cart;
            cartTemp = cart;

            ViewBag.CounterCart = cartTemp.Count;
            /////////////////////////////////////////////////////////////////////////////////
            TempData["carTempData"] = ViewBag.CounterCart;
            HttpContext.Session.SetString("CartNumOfItems", cartTemp.Count.ToString());

            return View("Cart");
        }


        public IActionResult OrderNow(int id)
        {
            if (HttpContext.Session.GetString("Cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(de.Product.Find(id), 1));
                HttpContext.Session.SetString("Cart", cart.ToString());
                ViewBag.cart = cart;
                cartTemp = cart;
            }
            else
            {
                List<Item> cart = cartTemp;
                int index = isExistingProduct(id);
                if (index == -1)
                    cart.Add(new Item(de.Product.Find(id), 1));
                else
                    cart[index].Quantity++;
                
                HttpContext.Session.SetString("Cart", cart.ToString());
                ViewBag.cart = cart;
                cartTemp = cart;
            }

            ViewBag.CounterCart = cartTemp.Count;
            /////////////////////////////////////////////////////////////////////////////////
            TempData["carTempData"] = ViewBag.CounterCart;

            HttpContext.Session.SetString("CartNumOfItems", cartTemp.Count.ToString());


            return View("Cart");
        }
    }
}

GameConsuleWebStore/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameConsuleWebStore.Data;
using GameConsuleWebStore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GameConsuleWebStore.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly GameConsuleWebStoreContext _context;
        public StatisticsController(GameConsuleWebStoreContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            
            //Blocking Not Admin
            if (HttpContext.Session.GetString("UserType") != "Admin")
            {
                return RedirectToAction("Login", "Users", new { messageAlert = "You are not connected as Admin member." });
            }

            return View("PieStat");
        }
    }
}

GameConsuleWebStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameConsuleWebStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <header>

        @*------ Nav Bar --------*@
        <div class="top">
            <img src="~/images/psLogo.png" alt="logo" id="logops">
            <img src="~/images/Xbox_logo_(2019).png" alt="logo" id="logoxbox">
            <img src="~/images/Nintendo_red_logo.png" alt="logo" id="logonintendo">
            <img src="~/images/wii.png" alt="logo" id="logonwiiu">
            <!--<form asp-action="Search" asp-controller="Products">-->
            @*SearchBox*@
            <!--<input name="name" id="SearchBoxInput" placeholder="Search On Site" style="position: absolute; top: 3px; right: 1044px; height: 23px;" autocomplete="off" />
                <div id="DivLoading" class="spinner-border text-dark" role="status" style=" top: 6px; right: 1074px; position: absolute; width: 18px; height: 18px;">
                    <span class="sr-only">Loading...</span>
                </div>
                <button type="submit" value="Search"><img id="SearchImg" src="~/images/SearchIcon.png" style="height: 35px; width: auto; position: absolute; top: -2px; right: 1041px;" /></button>
            </form>-->
        </div>


        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" id="logonav" width="65" height="45" /> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto" style="margin:5px">
                    <li class=" nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Products" asp-action="Index" tabindex="-1" aria-disabled="true">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Orders" asp-action="ShowOrders" asp-route-id="@Context.Session.GetString("UserId")" tabindex="-1" aria-disabled="true">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index2" tabindex="-1" aria-disabled="true">About</a>
                    </li>


                    @*<li><a asp-controller="ShoppingCarts" asp-action="Index">Shop</a></li>*@

                    @{
                        if (Context.Session.GetString("UserType") == "Admin")
                        {
                            <li>
                                @*<a asp-controller="Users" asp-action="Dashboard">Dashboard</a>*@
                                <div class="btn-group">
                                    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Dashboard
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" asp-controller="Users" asp-action="Index">Edit Users</a>
                                        <hr />
                                        <a class="dropdown-item" asp-controller="Products" asp-action="Index">Edit Products</a>
                                        <hr />
                                        <a class="dropdown-item" asp-controller="Orders" asp-action="Index">Edit Orders</a>
                                        <hr />
                                        <a class="dropdown-item" asp-controller="Statistics" asp-action="Index">Store Stats</a>
                                    </div>
                                </div>
                            </li>

                        }
                        else
                        {

                        }

                    }
                </ul>
                @{
                    if (Context.Session.GetString("UserName") != null)
                    {

                        <div style="">
                            <img id="ShopCartImg" src="~/images/shopping-cart-of-checkered-design.svg" style="width:30px;height:auto" />
                            <a id="ShopCartLink" asp-controller="ShoppingCart" asp-action="Index">Cart</a>

                            @{
                                if (@Context.Session.GetString("CartNumOfItems") == null)
                                {
                                    <b>(0)</b>
                                }
                                else
                                {
                                    if (@Context.Session.GetString("CartNumOfItems").Equals("0"))
                                    {
                                        <b>(0)</b>
                                    }
                                    else
                                    {
                                        <b>(@Context.Session.GetString("CartNumOfItems"))</b>
                                    }
                                }
                            }
                        </div>
                        <div class="dropdown" style="">
                            <button class="btn dropdown-toggle" role="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img id="UserImgConnected" src="~/images/UserLogoConnected.png" />
                                <b>@Context.Session.GetString("UserName")</b>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Users" asp-action="Edit" asp-route-id="@Context.Session.GetString("UserId")">Edit User Details</a>
                                <hr />
                                <a class="dropdown-item" asp-controller="Orders" asp-action="ShowOrders" asp-route-id="@Context.Session.GetString("UserId")">My Order's</a>
                                <hr />
                                <a class="dropdown-item" asp-controller="Users" asp-action="LogOut">Log Out</a>
                            </div>
                        </div>
                        <div class="header_options">
                            <a asp-controller="Users" asp-action="LogOut">Log Out</a>
                        </div>
                    }
                    else
                    {
                        @*<div s">
                                <img id="ShopCartImg" src="~/images/shopping-cart-of-checkered-design.svg" style="width:30px;height:auto" />
                                <a id="ShopCartLink" asp-controller="ShoppingCart" asp-action="Index">Cart</a>

                                @{
                                    if (@Context.Session.GetString("CartNumOfItems") == null)
                                    {
                                        <b>(0)</b>
                                    }
                                    else
                                    {
                                        if (@Context.Session.GetString("CartNumOfItems").Equals("0"))
                                        {
                                            <b>(0)</b>
                                        }
                                        else
                                        {
                                            <b>(@Context.Session.GetString("CartNumOfItems"))</b>
                                        }
                                    }
                                }
                            </div>*@

                        <div class="header_options">
                            <a asp-controller="Users" asp-action="Register">Sign up</a>
                            <a asp-controller="Users" asp-action="Login">Login</a>
                        </div>
                    }
                }

            </div>
        </nav>





    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

        <div class="container">

            &copy; 2020 - GameConsuleWebStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://d3js.org/d3.v4.js"></script>
    <script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>